export default function changeMonth(date) {
  return date === "01"
    ? "sty"
    : date === "02"
    ? "lut"
    : date === "03"
    ? "mar"
    : date === "04"
    ? "kwi"
    : date === "05"
    ? "maj"
    : date === "06"
    ? "cze"
    : date === "07"
    ? "lip"
    : date === "08"
    ? "sie"
    : date === "09"
    ? "wrz"
    : date === "10"
    ? "paź"
    : date === "11"
    ? "lis"
    : "gru";
}
